# Generated by Django 2.2.10 on 2021-09-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('time_slice', models.CharField(max_length=30)),
                ('number_of_transitions', models.IntegerField()),
            ],
        ),
    ]
